# https://taskfile.dev

version: '3'

tasks:
  default:
    cmds:
      - task: build

  install-dependencies:
    deps: []
    status:
      - xxd --version
      - gettext --version
    cmds:
      - cmd: sudo apt-get update
      - cmd: |
          sudo apt-get install --yes --no-install-recommends \
            xxd gettext

  # This is a copy of 'autogen.sh' with some modifications.
  autogen:
    deps: [install-dependencies]
    cmds:
      - cmd: |
          # Install config.rpath which is needed for AM_ICONV macro
          for dir in "$GETTEXT_DIR" /usr/share/gettext /usr/local/share/gettext; do
            if test -f "$dir/config.rpath"; then
              test -f config.rpath || echo "autogen.sh: installing './config.rpath'"
              cp -f "$dir/config.rpath" .
              break
            fi
          done
      # These commands essentially replicate the 'autoreconf -vfi' command.
      - cmd: aclocal --force
      - cmd: autoconf --force
      - cmd: automake --add-missing --copy --force-missing --include-deps

  build:
    deps: [autogen]
    env:
      LDFLAGS: --static
      CONFIGURE_FLAGS: --without-iconv
      CFLAGS: -W -Wall -O2 -g -fwrapv -fsanitize=address
    cmds:
      - cmd: ./configure $CONFIGURE_FLAGS
      - cmd: make

  check:
    deps: [build]
    cmds:
      - cmd: make check
