# https://taskfile.dev

version: '3'

tasks:
  default:
    cmds:
      - task: build

  build:
    cmds:
      - cmd: automake --add-missing
      - cmd: ./autogen.sh
      - cmd: ./configure
      - cmd: make
